### ISSUE TITLE
Test Mode: How it works, what it does, how to send signals in test mode

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/docs#31]
## Reason

- While you develop and/or test your TelemetryDeck-enabled app, you'll also send signals
- but these signals are not from actual users
- so your analytics results are skewed, which is not cool.
- But not sending any signals means you won't be able to find errors in the configuration of the TelemetryDeck SDK 
- not sending signals means you don't know if things work until you release the app
- Not sending signals means you can't prepare your insights for any new signal types or payload types until you've released the app
- So we've created Test Mode to distinguish between real signals and signals sent during development and testing

## Tags

- testmode
- setup 
- quickstart

## How it works

- every signal has an `isTestMode` parameter that can either be `true` or `false` 
- in the dashboard use the "Test Mode" toggle to either only show signals with isTestMode == true or isTestMode == false

## How to send signals in test mode

- The SDKs try to infer the `isTestMode` parameter as best as they can, for example if a `DEBUG` parameter is present in your development environment, that is used as the value for `isTestMode`
- You can also override the `isTestMode` parameter just as you would add any other payload parameter to a signal
- Note: since signal payloads only support strings, the parameter needs to be either `"true"` or `"false"`

### Manually set Test Mode in Swift SDK

```swift
// An example variable to manually set test mode.
// Set this to `true` or `false` depending on your app's configuration
// or environment or state
let customTestModeParameter = true

TelemetryManager.send(
    "pizzaModeActivated",
    for: "myUserIdentifier",
    with: ["isTestMode": customTestModeParameter ? "true" : "false"]
)
```

### Manually set test mode in JavaScript SDK

```javascript
// Example initialisation of TelemetryDeck SDK
td = new TelemetryDeck({
  app: ENV.APP.telemetryAppID,
  user: this.user.current?.email ?? 'anonymous',
});

// In our example, the app has a `send` function wrapping the TelemetryDeck SDK
send(payload) {
  // ENV.APP.telemetryIsDebug is an example variable that represents your app's
  // configuration or environment. Replace it with an implementation that fits your
  // app's needs.
  if (ENV.APP.telemetryIsDebug) {
    this.td.signal({...payload, isTestMode: "true"})
    return;
  }

  this.td.signal(payload);
}
```

**Comment by winsmith** [comment]
@voidedmain I've updated the ticket with a bit more information -- sorry for the delay. Let me know if you have any questions about the content!

**Comment by winsmith** [comment]
Just realised there is already an article on test mode: `articles/test-mode.md`! I think we should update that article instead of writing a new one

**Comment by voidedmain** [comment]
Thanks for letting me know! Will have a look at it as soon as possible.
