### ISSUE TITLE
Missing image in article "apple app privacy details''

### ISSUE THREAD

**Issue by voidedmain** [TelemetryDeck/docs#34]
The article seems to be missing an image:
![Image](https://user-images.githubusercontent.com/21177480/187145256-b59d9e12-8289-49b5-a707-7b1cd83b424f.PNG)

The options I see we have:
1. figuring out where the image went 🔍  (@winsmith)
2. getting rid of the segment in the article (@voidedmain)

**Comment by voidedmain** [comment]
Good news: the picture is still [there!](https://github.com/TelemetryDeck/website/blob/00c766bef6b42aca67d365ea1e83ce2cb9c5017c/content/images/privacy-overview.png) It also seems to be the correct path? I can't figure out why it won't get displayed tho 😕

**Comment by winsmith** [comment]
I added the image in #35, after writing code that allows you to actually display images :D~ 

I also added documentation on how to add images to docs pages here: https://delightful-plant-0a2373503.1.azurestaticapps.net/docs/articles/documentation/#images
