### ISSUE TITLE
Insights Reference

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/docs#36]
**Insight** - An _Insight_ is one of the primary building blocks of TelemetryDeck. In essence, you can think of an insight as one of the little cards with data in an insight group. They have a title, a _Query_, and a _Display Mode_. The query is used to retrieve data from the TelemetryDeck API, and the display mode is used to determine how the data is displayed, e.g. as a bar chart, or a line chart.

- Insights as a concept
- Use 'the insight's card' to distinguish between insights the concept and the UI 

Todos:

- [ ] Move `api/insights-reference.md` to `articles/`
- [x] Go through and remove things that are no longer relevant 
  - [x] Subtitle
  - [x] "Raw" is now called table
  - [x] "Group values by" is now called "Granularity"
  - [x] Signal type doesn't need typing anymore -> dropdown
  - [x] Rename "breakdown" to "Top N" query
  - [x] Filters: remove note
- [x] Generated Query 
  - [x] you can optionally convert your insight into a "custom query insight". This allows you to edit the database query in the insight directly, giving you more control. (note: there is no going back)
  - [x] a custom query is JSON object in the telemetrydeck query language, which is a superset of the Druid Query Language. See the [Druid query documentation](https://druid.apache.org/docs/latest/querying/querying.html) for a jump start.
  - [x] In addition to the druid features custom queries in the telemetrydeck query language can contain a relative time interval https://blog.telemetrydack.com/docs/tql/time-intervals/
  - [x] During execution, we will automatically wrap your query in a filter that makes it apply to all your organisation's apps. To query a single app, filter for that app's app ID.

**Comment by voidedmain** [comment]
@winsmith the images I added to the article don't show up on the page. I already checked the file location, and they are all present. Don't know what's causing the behavior.

**Comment by winsmith** [comment]
The problem is the image names are case sensitive. The image names are named `something.PNG` but you added `something.png` and the server is of the opinion those are two different file names. I changed them and it works now :)
