### ISSUE TITLE
Documentation: Typo in Javascript Setup Page

### ISSUE THREAD

**Issue by janrebolledo** [TelemetryDeck/docs#56]
Typo in code snippet

In first code snipped under **"Advanced usage as a Package for applications that use a bundler (like Webpack, Rollup, …)"**

```js
const queuedEvents = [
  ["app", YOUR_APP_ID],
  ["user", YOUR_USER_IDENTIFIER],
  ["signal"],
  ["signal", { route: "some/page/path" }],
];
td.ingest(qeuedEvents); // <--
```

The variable `queuedEvents` is misspelled.

**Comment by winsmith** [comment]
Oops, thank you!
