### ISSUE TITLE
Feedback for https://telemetrydeck.com/docs/guides/swift-setup/

### ISSUE THREAD

**Issue by michaellenaghan** [TelemetryDeck/docs#59]
**Is your feedback related to a problem? Please describe.**

The [Swift Setup Guide](https://telemetrydeck.com/docs/guides/swift-setup/) ends with:

> ## You’re all set!
>
> You can now send signals! …

But there's a critical missing step. Before you can actually _ship_ an iOS app that uses TelemetryDeck, you have to answer [Apple's app privacy questions](https://developer.apple.com/app-store/app-privacy-details/).

**Describe the solution you'd like or the information you're missing**

* Let your iOS developers know that they have to answer Apple's app privacy questions; and
* Provide a link to [your guidance](https://telemetrydeck.com/docs/articles/apple-app-privacy/) on _how_ to answer.

**Comment by voidedmain** [comment]
Thank you for pointing this out! I added it to the Swift guide :)
