### ISSUE TITLE
How to invite users to join your organization

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/docs#6]
Reason: 
- if there are more people in your organization, they should have their own user account
- share groups and insights
- collaborate 
- show reports, dashboards, insights to other members of your team

Tags: 
- beginner
- howto
- user-cohorts
- collaboration

Steps:
- In the telemetrydeck dashboard, select the user menu by clicking on your name in the top right
- select "organization settings"
- in the list, enter the person's email address - we will send them an email with a registration link

**Comment by voidedmain** [comment]
- [ ] #24 
- [ ] #25
