### ISSUE TITLE
Update articles based on recent UI/feature changes

### ISSUE THREAD

**Issue by voidedmain** [TelemetryDeck/docs#61]
!Important: **Use images** instead of text to show where features are located, this makes it easier to edit in the future, and it visualizes it for the website visitors.

Articles that need to be edited:

- [x] [Custom dashboards with insights groups](https://telemetrydeck.com/docs/articles/create-custom-dashboards/)
  - [x] Create and delete insights from your group
  - [x] Rename your group
  - [x] Delete your group

- [x] [Track the number of daily active users in your app](https://telemetrydeck.com/docs/articles/insights-about-daily-users/)
  - [x] Select or create a new group
  - [x] Creating a new insight
  - [x] Configure your insights to show daily active users

- [x] [Find out which operating system your users are using](https://telemetrydeck.com/docs/articles/insights-about-system-version/)
  - [x] Step one: Navigate to your app
  - [x] Step two: Select or create a new group
  - [x] Step three: Creating a new insight
  - [x] Step four: Configure your insights-

- [x] [Detect if users update to the latest app version](https://telemetrydeck.com/docs/articles/check-if-users-upgrade-to-latest-app-version/)
  - [x] Use our app overview
  - [x] Create a custom insight
  - [x] Configuring your insight

**Comment by winsmith** [comment]
Thank you! I know this is not always easy. I'm trying to point out changes in the slack channel so you're aware of them!
