### ISSUE TITLE
Docs: Spacing between "next" and "previous" is too small the larger the text is

### ISSUE THREAD

**Issue by voidedmain** [TelemetryDeck/docs#62]
Screenshot was taken with a browser window where the width was larger then the element. Text probably needs a wrapping to the next line.

The documentation that is seen in the screenshot: https://telemetrydeck.com/docs/articles/check-if-users-upgrade-to-latest-app-version/

![Image](https://user-images.githubusercontent.com/21177480/232077662-46cbbf8a-a13f-429a-a9e9-2f6fa0c08552.png)

**Comment by winsmith** [comment]
The text now wraps 🥇
