### ISSUE TITLE
Anonymization Article

### ISSUE THREAD

**Issue by voidedmain** [TelemetryDeck/docs#64]
from Mail:

Our SDKs optionally accept a custom user identifier such as an email address or an internal identifier. If you don’t supply that identifier, we generate a random one for you, or — depending on the platform — ask the operating system for one, such as the iOS „identifierForVendor“. 

We salt and hash that identifier on device. You can optionally provide a salt string for that as well using the configuration object. 

when a signal arrives on the server, we add our own salt to its user identifiers and hash it again. This way neither TelemetryDeck nor you can reconstruct the original identifier, preserving privacy. 

if you use the same (custom) salt and provide the same original ID you’ll recognize the same user from different platforms.

**Comment by winsmith** [comment]
Fantastic work!
