### ISSUE TITLE
Feedback for articles/update-package.md

### ISSUE THREAD

**Issue by bshirley** [TelemetryDeck/docs#66]
There is an additional situation some may be inquiring about with this question.

They could be asking "how do I change the configuration I setup for this package dependency".

If they do either or both of the items listed in your answer and don't get what they need, it's likely the way they've configured it. They could have said "only use version 1.2.3" or "user 1.2.3 up to the Next Minor release", this will not allow them to update to 2.0.0.

If they need to update their specification of the dependency, that is described [here](https://stackoverflow.com/a/67609773/201042).

Please consider adding that to your answer.
Your SEO is very good, and it would be nice to get the complete answer.

**Comment by winsmith** [comment]
Thanks, this is awesome feedback!
