### ISSUE TITLE
Feedback for guides/web-setup.md

### ISSUE THREAD

**Issue by DivineDominion** [TelemetryDeck/docs#72]
The guide is very good to get started 👍

So I was setting up the signal to check out TelemetryDeck for our website and wondered about two things:

1. Since the 'app' starts in test mode, how can I toggle the test mode flag? E.g. for our staging server.
    -  Proposed solution: mention explicitly that this isn't possible, if it isn't possible, or add a code snippet with the "is testing" flag set.
2. How can we ensure that nobody 'steals' our App ID? It'd be mostly a prank, but what if a troll copies the script + app ID snippet from our HTML and sends fake signals for their website?
    - Proposed solution: Add a list of acceptable domains/origin to the web/app config settings somewhere and mention that on this guide.

**Comment by winsmith** [comment]
Great idea, I added this hint:

> By default, all signals sent from `localhost` or an IP address in the [private IP address ranges](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces) are automatcially marked as Test signals. This is to prevent test signals from polluting your data. To see test signals, you can enable **Test Mode** in the Dashboard.

Also, as of today we're separately collecting a `host` property in the Web SDK that can be used to validate things are running on the correct host.
