### ISSUE TITLE
Feedback for tql/topNMetricSpec.md: what's previousStop?

### ISSUE THREAD

**Issue by DivineDominion** [TelemetryDeck/docs#74]
In the example on this page:

```
{
  "type": "dimension",
  "ordering": "lexicographic",
  "previousStop": "<previousStop_value>"
}
```

I have no clue  what   `"previousStop": "<previousStop_value>"` is supposed to be.

**Comment by winsmith** [comment]
Added the following description just now.

> `previousStop` is an optional string and the starting point of the sort. For example, if a `previousStop` value is `b`, all values before `b` are discarded. This field can be used to paginate through all the dimension values.

Here's a tip btw: TQL is a superset of the Druid Query Language, so a lot of the times you can find more info in the Apache Druid Docs: https://druid.apache.org/docs/latest/querying/topnmetricspec

Thanks so much for your tickets and PRs, they are greatly appreciated!!
