### ISSUE TITLE
We need continuous support for synchronous API

### ISSUE THREAD

**Issue by erdemeylul** [TelemetryDeck/docs#92]
We plan to build an integration with Telemetry Deck where the users can display their KPIs on Apple devices. However, our codebase is not compatible with asynchronous API for running queries. It is mentioned in the documents that synchronous API will be deprecated. We need a continuous support for synchronous API.

**Comment by erdemeylul** [comment]
The feature we would prefer is this:

- An endpoint to list all the dashboards
- An endpoint to list all the queries on a dashboard
- An endpoint to run the query synchronously

**Comment by winsmith** [comment]
Hi @erdemeylul, thanks for reaching out. Here is example code in SwiftUI on how to access these APIs. Have a look at the `Cluster` structs especially, you can totally just copy that out for your code.
