### ISSUE TITLE
Feedback for https://telemetrydeck.com/docs/guides/swift-setup/#sending-signals

### ISSUE THREAD

**Issue by warpling** [TelemetryDeck/docs#99]
**Is your feedback related to a problem? Please describe.**
Setting the UserID for every signal is tedious.

**Describe the solution you'd like or the information you're missing**
There is a way to set it once but it's not in the docs: `TelemetryDeck.updateDefaultUserID(to: …)`

**Comment by winsmith** [comment]
Oh yeah, the docs are outdated here. @voidedmain, could you please update the article as follows: 

- The default way to set a user identifier is `TelemetryDeck.updateDefaultUserID`. This way you only have to set it once, or when it changes (such as user login)
- Maybe add an "info" box that you can also set a user identifier per `send` call, but this is not usually necessary
